import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Container from 'react-bootstrap/Container';
import MovieCard from '@/components/MovieCard';

export default function Home(props) {

  const [movies, setMovies] = useState(props.movies)

  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Container className={styles.homeContainer}>
          {movies.map((movie, index) => {
            return <MovieCard key={index} movie={movie} />
          })}
        </Container>
      </main>
    </>
  )
}

export const getServerSideProps = async (context) => {
  const host = process.env.NEXT_PUBLIC_SERVER_URL
  const response = await fetch(`${host}/get-movies`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
      //Accept: 'application/json'
    }
  });
  const json = await response.json()
  if (json.success) {
    return {
      props: {
        success: true,
        movies: json.movies
      }
    }
  }
  return {
    props: {
      success: false,
      movies: []
    }
  }
};
